development:
  adapter: mysql2
  encode: utf8
  database: roots
  pool: 5
  timeout: 5000
  username: root
  password: 'alfa1625'

test:
  adapter: mysql2
  encode: utf8
  database: roots_test
  pool: 5
  timeout: 5000
  username: root
  password: 'alfa1625'


production:
  adapter: mysql2
  encode: utf8
  database: roots
  pool: 5
  timeout: 5000
  username: root
  password: 'alfa1625'
